---
- hosts: jenkins-slaves
  name: jenkin-slave playbook
  remote_user: ubuntu
  gather_facts: false
  become: yes
  tasks:
    - name: Update apt package
      apt:
        update_cache: yes

    - name: Install Java 11
      package:
        name: openjdk-11-jdk
        state: present

    - name: Install SSH server
      apt:
        name: openssh-server
        state: present

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
        state: present

    - name: Add Docker Repository Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    
    - name: Update apt package
      apt:
        update_cache: yes
    
    - name: Install Docker
      apt:
        name: 
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
        state: present
    
    - name: Restart Docker service
      service:
        name: docker
        state: restarted
    
    - name: Create jenkins directory
      file:
        path: "/home/ubuntu/jenkins"
        state: directory
        owner: "ubuntu"
        group: "ubuntu"
        mode: "0777"

    - name: Add user 'ubuntu' to the 'docker' group
      user:
        name: ubuntu
        groups: docker
        append: yes
